import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsContextProvider } from "@/components/ProductsContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProductsContextProvider>
        {children}
      </ProductsContextProvider>
        </body>
    </html>
  );
}
